export default [
  {id: 1, name: 'C2', keyCode: '49', key: '1', note: '36', type: 'white'},
  {id: 2, name: 'D2', keyCode: '50', key: '2', note: '38', type: 'white'},
  {id: 3, name: 'E2', keyCode: '51', key: '3', note: '40', type: 'white'},
  {id: 4, name: 'F2', keyCode: '52', key: '4', note: '41', type: 'white'},
  {id: 5, name: 'G2', keyCode: '53', key: '5', note: '43', type: 'white'},
  {id: 6, name: 'A2', keyCode: '54', key: '6', note: '45', type: 'white'},
  {id: 7, name: 'B2', keyCode: '55', key: '7', note: '47', type: 'white'},
  {id: 8, name: 'C3', keyCode: '56', key: '8', note: '48', type: 'white'},
  {id: 9, name: 'D3', keyCode: '57', key: '9', note: '50', type: 'white'},
  {id: 10, name: 'E3', keyCode: '48', key: '0', note: '52', type: 'white'},
  {id: 26, name: 'F3', keyCode: '81', key: 'Q', note: '53', type: 'white'},
  {id: 32, name: 'G3', keyCode: '87', key: 'W', note: '55', type: 'white'},
  {id: 14, name: 'A3', keyCode: '69', key: 'E', note: '57', type: 'white'},
  {id: 27, name: 'B3', keyCode: '82', key: 'R', note: '59', type: 'white'},
  {id: 29, name: 'C4', keyCode: '84', key: 'T', note: '60', type: 'white'},
  {id: 34, name: 'D4', keyCode: '89', key: 'Y', note: '62', type: 'white'},
  {id: 30, name: 'E4', keyCode: '85', key: 'U', note: '64', type: 'white'},
  {id: 18, name: 'F4', keyCode: '73', key: 'I', note: '65', type: 'white'},
  {id: 24, name: 'G4', keyCode: '79', key: 'O', note: '67', type: 'white'},
  {id: 25, name: 'A4', keyCode: '80', key: 'P', note: '69', type: 'white'},
  {id: 10, name: 'B4', keyCode: '65', key: 'A', note: '71', type: 'white'},
  {id: 28, name: 'C5', keyCode: '83', key: 'S', note: '72', type: 'white'},
  {id: 13, name: 'D5', keyCode: '68', key: 'D', note: '74', type: 'white'},
  {id: 15, name: 'E5', keyCode: '70', key: 'F', note: '76', type: 'white'},
  {id: 16, name: 'F5', keyCode: '71', key: 'G', note: '77', type: 'white'},
  {id: 17, name: 'G5', keyCode: '72', key: 'H', note: '79', type: 'white'},
  {id: 19, name: 'A5', keyCode: '74', key: 'J', note: '81', type: 'white'},
  {id: 20, name: 'B5', keyCode: '75', key: 'K', note: '83', type: 'white'},
  {id: 21, name: 'C6', keyCode: '76', key: 'L', note: '84', type: 'white'},
  {id: 35, name: 'D6', keyCode: '90', key: 'Z', note: '86', type: 'white'},
  {id: 33, name: 'E6', keyCode: '88', key: 'X', note: '88', type: 'white'},
  {id: 12, name: 'F6', keyCode: '67', key: 'C', note: '89', type: 'white'},
  {id: 31, name: 'G6', keyCode: '86', key: 'V', note: '91', type: 'white'},
  {id: 11, name: 'A6', keyCode: '66', key: 'B', note: '93', type: 'white'},
  {id: 23, name: 'B6', keyCode: '78', key: 'N', note: '95', type: 'white'},
  {id: 22, name: 'C7', keyCode: '77', key: 'M', note: '96', type: 'white'},

  {id: 36, name: 'C#2', keyCode: 'b49', key: '⇧<br>+<br>1', note: '37', type: 'black'},
  {id: 37, name: 'D#2', keyCode: 'b50', key: '⇧<br>+<br>2', note: '39', type: 'black'},
  {id: 38, name: 'F#2', keyCode: 'b52', key: '⇧<br>+<br>4', note: '42', type: 'black'},
  {id: 39, name: 'G#2', keyCode: 'b53', key: '⇧<br>+<br>5', note: '44', type: 'black'},
  {id: 40, name: 'A#2', keyCode: 'b54', key: '⇧<br>+<br>6', note: '46', type: 'black'},
  {id: 41, name: 'C#3', keyCode: 'b56', key: '⇧<br>+<br>8', note: '49', type: 'black'},
  {id: 42, name: 'D#3', keyCode: 'b57', key: '⇧<br>+<br>9', note: '51', type: 'black'},
  {id: 43, name: 'F#3', keyCode: 'b81', key: '⇧<br>+<br>Q', note: '54', type: 'black'},
  {id: 44, name: 'G#3', keyCode: 'b87', key: '⇧<br>+<br>W', note: '56', type: 'black'},
  {id: 45, name: 'A#3', keyCode: 'b69', key: '⇧<br>+<br>E', note: '58', type: 'black'},
  {id: 46, name: 'C#4', keyCode: 'b84', key: '⇧<br>+<br>T', note: '61', type: 'black'},
  {id: 47, name: 'D#4', keyCode: 'b89', key: '⇧<br>+<br>Y', note: '63', type: 'black'},
  {id: 48, name: 'F#4', keyCode: 'b73', key: '⇧<br>+<br>I', note: '66', type: 'black'},
  {id: 49, name: 'G#4', keyCode: 'b79', key: '⇧<br>+<br>O', note: '68', type: 'black'},
  {id: 50, name: 'A#4', keyCode: 'b80', key: '⇧<br>+<br>P', note: '70', type: 'black'},
  {id: 51, name: 'C#5', keyCode: 'b83', key: '⇧<br>+<br>S', note: '73', type: 'black'},
  {id: 52, name: 'D#5', keyCode: 'b68', key: '⇧<br>+<br>D', note: '75', type: 'black'},
  {id: 53, name: 'F#5', keyCode: 'b71', key: '⇧<br>+<br>G', note: '78', type: 'black'},
  {id: 54, name: 'G#5', keyCode: 'b72', key: '⇧<br>+<br>H', note: '80', type: 'black'},
  {id: 55, name: 'A#5', keyCode: 'b74', key: '⇧<br>+<br>J', note: '82', type: 'black'},
  {id: 56, name: 'C#6', keyCode: 'b76', key: '⇧<br>+<br>L', note: '85', type: 'black'},
  {id: 57, name: 'D#6', keyCode: 'b90', key: '⇧<br>+<br>Z', note: '87', type: 'black'},
  {id: 58, name: 'F#6', keyCode: 'b67', key: '⇧<br>+<br>C', note: '90', type: 'black'},
  {id: 59, name: 'G#6', keyCode: 'b86', key: '⇧<br>+<br>V', note: '92', type: 'black'},
  {id: 60, name: 'A#6', keyCode: 'b66', key: '⇧<br>+<br>B', note: '94', type: 'black'},
]

export const NotesMap = [
  { name: 'C2', file: 'a49' },
  { name: 'D2', file: 'a50' },
  { name: 'E2', file: 'a51' },
  { name: 'F2', file: 'a52' },
  { name: 'G2', file: 'a53' },
  { name: 'A2', file: 'a54' },
  { name: 'B2', file: 'a55' },
  { name: 'C3', file: 'a56' },
  { name: 'D3', file: 'a57' },
  { name: 'E3', file: 'a48' },
  { name: 'F3', file: 'a81' },
  { name: 'G3', file: 'a87' },
  { name: 'A3', file: 'a69' },
  { name: 'B3', file: 'a82' },
  { name: 'C4', file: 'a84' },
  { name: 'D4', file: 'a89' },
  { name: 'E4', file: 'a85' },
  { name: 'F4', file: 'a73' },
  { name: 'G4', file: 'a79' },
  { name: 'A4', file: 'a80' },
  { name: 'B4', file: 'a65' },
  { name: 'C5', file: 'a83' },
  { name: 'D5', file: 'a68' },
  { name: 'E5', file: 'a70' },
  { name: 'F5', file: 'a71' },
  { name: 'G5', file: 'a72' },
  { name: 'A5', file: 'a74' },
  { name: 'B5', file: 'a75' },
  { name: 'C6', file: 'a76' },
  { name: 'D6', file: 'a90' },
  { name: 'E6', file: 'a88' },
  { name: 'F6', file: 'a67' },
  { name: 'G6', file: 'a86' },
  { name: 'A6', file: 'a66' },
  { name: 'B6', file: 'a78' },
  { name: 'C7', file: 'a77' },

  { name: 'C#2', file: 'b49' },
  { name: 'D#2', file: 'b50' },
  { name: 'F#2', file: 'b52' },
  { name: 'G#2', file: 'b53' },
  { name: 'A#2', file: 'b54' },
  { name: 'C#3', file: 'b56' },
  { name: 'D#3', file: 'b57' },
  { name: 'F#3', file: 'b81' },
  { name: 'G#3', file: 'b87' },
  { name: 'A#3', file: 'b69' },
  { name: 'C#4', file: 'b84' },
  { name: 'D#4', file: 'b89' },
  { name: 'F#4', file: 'b73' },
  { name: 'G#4', file: 'b79' },
  { name: 'A#4', file: 'b80' },
  { name: 'C#5', file: 'b83' },
  { name: 'D#5', file: 'b68' },
  { name: 'F#5', file: 'b71' },
  { name: 'G#5', file: 'b72' },
  { name: 'A#5', file: 'b74' },
  { name: 'C#6', file: 'b76' },
  { name: 'D#6', file: 'b90' },
  { name: 'F#6', file: 'b67' },
  { name: 'G#6', file: 'b86' },
  { name: 'A#6', file: 'b66' }
]